(function($){$(document).ready(function(){if($('body').hasClass('search')){return}
$('.accordion-wrapper a.button.accordion-header').click(function(event){event.preventDefault()})
var current_url=window.location.href;var query_param=current_url.split('?')[1];if(typeof query_param!='undefined'&&query_param!=null){let form_data=new FormData();form_data.append('action','sa-addons-save-query-param');form_data.append('_wpnonce',sixAmAddons.nonce);form_data.append('command','usage-breakdown');form_data.append('data',query_param);axios.post(sixAmAddons.ajaxurl,form_data,{headers:{"Content-Type":"form-data",},}).then(function(response){})
$('a[target=_blank').on('click',function(e){e.preventDefault();var externalLink=$(this).attr('href');var combinator=externalLink.match(/\?/)?'&':'?';var newLink=externalLink+combinator+query_param;window.open(newLink,'_blank')});$('a:not([target=_blank])').on('click',function(e){if($(this).attr('href')==''||typeof $(this).attr('href')=='undefined'){return}
e.preventDefault();var externalLink=$(this).attr('href');var combinator=externalLink.match(/\?/)?'&':'?';var newLink=externalLink+combinator+query_param;window.location.href=newLink})}else{query_param=sixAmAddons.savedParam;if(typeof query_param!='undefined'&&query_param!=null){$('a[target=_blank').on('click',function(e){if($(this).attr('href').match('https://codecanyon')){e.preventDefault();var externalLink=$(this).attr('href');var combinator=externalLink.match(/\?/)?'&':'?';var newLink=externalLink+combinator+query_param;window.open(newLink,'_blank')}})}}
$('div[sa-element-wrapper-link]').click(function(){var encoded_link=$(this).attr('sa-element-wrapper-link');var link_attr=JSON.parse(encoded_link);var link_url=link_attr.url;if(typeof query_param!='undefined'&&query_param!=null){var combinator=link_url.match(/\?/)?'&':'?';link_url=link_url+combinator+query_param}
var link_target=link_attr.is_external=='on'?'_blank':'_self';window.open(link_url,link_target)});$('.close_bundle_popup').click(function(event){event.preventDefault();$('.bundle_popup_modal').fadeOut()})
let hasShown=!1;const maxShowCount=2;const hideDurationDays=2.9;function canShowSection(){const showData=JSON.parse(localStorage.getItem('saShowBnr'))||{showCount:0,lastShown:null};const now=new Date();const lastShownDate=new Date(showData.lastShown);let dateDiff=(lastShownDate-now)/(1000*60*60*24);if(hasShown){return!1}
if(showData.showCount<maxShowCount){return!0}else if(dateDiff>=hideDurationDays){localStorage.setItem('saShowBnr',JSON.stringify({showCount:0,lastShown:null}));return!0}
return!1}
function showSection(){if(!canShowSection()){return}
$('.bundle_popup_modal').show();const showData=JSON.parse(localStorage.getItem('saShowBnr'))||{showCount:0,lastShown:null};showData.showCount+=1;showData.lastShown=new Date();localStorage.setItem('saShowBnr',JSON.stringify(showData));hasShown=!0}
if($(window).width()<1025){$(window).on('scroll',function(){let scrollPosition=$(window).scrollTop();let windowHeight=$(window).height();let documentHeight=$(document).height();let scrollPercentage=(scrollPosition+windowHeight)/documentHeight*100;if(scrollPercentage>=50&&$('.bundle_popup_modal').is(':hidden')){showSection()}})}else{$(document).mouseleave(function(event){if(event.clientY<=0){showSection()}})}})})(jQuery)
;